# Generated by Django 2.0.3 on 2018-03-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='fecha_pub',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='votos',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
