# Generated by Django 2.0.3 on 2018-03-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_auto_20180312_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='votos',
            field=models.IntegerField(default=0),
        ),
    ]
